name: "Close Outdates Issues"
description: "Closes issues with past dates in the titles"
inputs:
  token:
    description: "GitHub token"
    required: true
  owner:
    description: "owner name of the target repo"
    required: true
  repo:
    description: "name of the target repo"
    required: true
runs:
  using: "node12"
  main: "index.js"
branding:
  icon: "check-square"
  color: "purple"
