name: "Close Outdated Issues"
description: "Closes issues with past dates in the titles"
inputs:
  token:
    description: "GitHub token"
    required: true
runs:
  using: "node12"
  main: "index.js"
branding:
  icon: "check-square"
  color: "purple"
