name: "Move Over"
description: "Moves card from one project column to another based on a given pattern."
inputs:
  token:
    description: "GitHub token"
    required: true
  owner:
    description: "owner name of the target repo"
    required: true
  repo:
    description: "name of the target repo"
    required: true
runs:
  using: "node12"
  main: "index.js"
