name: Test
on:
  workflow_dispatch:
  push:
    paths:
    - '**.js'
jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Action
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
