name: Test
on: [push]
jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run Action
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
